

 cpi \\sadc1sccmp1\OSD\Drivers\Panasonic\CF-C1\Unpacked\util2 -destination c:\util2\ -recurse

  
    $commandLine0 =  "c:\util2\pcommon\pinstall.bat"
    $commandLine1 = "c:\util2\pcomn64\pinstall.bat" 
	$commandLine2 = "c:\util2\drivers\newmisc\pinstall.bat"
  $commandLine3 =   "c:\util2\drivers\hotkey\pinstall.bat"
$commandLine4 = "c:\util2\pcommon\pinstall.bat"
$commandLine5 = "c:\util2\pcomn64\pinstall.bat"
$commandLine6 = "c:\util2\drivers\newmisc\pinstall.bat"
$commandLine7 = "c:\util2\drivers\mouse\pinstall.bat"
$commandLine8 = "c:\util2\drivers\modem\pinstall.bat"
$commandLine9 = "c:\util2\ipt\pinstall.bat"
$commandLine10 = "c:\util2\brecal\pinstall.bat"
$commandLine11 = "c:\util2\hkeyapp\pinstall.bat"
$commandLine12 = "c:\util2\hkeyset\pinstall.bat"
$commandLine13 = "c:\util2\pnotif\pinstall.bat"
$commandLine14 = "c:\util2\ppopup\pinstall.bat"
$commandLine15 = "c:\util2\pcinfo\pinstall.bat"
$commandLine16 = "c:\util2\pplanex\pinstall.bat"
$commandLine17 = "c:\util2\selsussv\pinstall.bat"
$commandLine18 = "c:\util2\wheelpad\pinstall.bat"
$commandLine19 = "c:\util2\wdisable\pinstall.bat"
$commandLine20 = "c:\util2\wswitch\pinstall.bat"
$commandLine21 = "c:\util2\loupe\pinstall.bat"
$commandLine22 = "c:\util2\drivers\video\pinstall.bat"
$commandLine23 = "c:\util2\meiskb\pinstall.bat"
$commandLine24 = "c:\util2\drivers\meitbtn\peinstall.bat"
$commandLine25 = "c:\util2\drivers\meitbtn\standard_c1_64.bat"
$commandLine26 = "c:\util2\drivers\sd_ri\pinstall.bat"
$commandLine27 = "copy c:\util2\drivers\sd_ri\sdpabus.dll c:\windows\syswow64\sda\"
$commandLine28 = "c:\util2\drivers\dtouch\pinstall.bat"
$commandLine29 = "c:\util2\drivers\etm\pinstall.bat"
$commandLine30 = "c:\util2\drivers\wlan\pinstall.bat"
$commandLine31 = "c:\util2\calibutl\pinstall.bat"
$commandLine32 = "c:\util2\pcam\pinstall.bat"
$commandLine33 = "c:\util2\dboard\pinstall.bat"
$commandLine34 = "c:\util2\disprot\pinstall.bat"
$commandLine35 = "c:\util2\writing\pinstall.bat"
$commandLine36 = "c:\util2\drivers\touch\pinstall.bat"
$commandLine37 = "c:\util2\qbmgr2\pinstall.bat"
$commandLine38 = "c:\util2\meitbman\pinstall.bat"
$commandLine39 = "c:\util2\drivers\sound\pinstall.bat"
$commandLine40 = "c:\util2\drivers\smartc\pinstall.bat"
$commandLine41 = "c:\util2\drivers\tpm\Infineon\setup.exe"


    
    $results0 = invoke-expression -command "$commandLine0"
	$results1 = invoke-expression -command "$commandLine1"
	$results2 = invoke-expression -command "$commandLine2"
    $results3 = invoke-expression -command "$commandLine3"
$results4 = invoke-expression -command "commandline4"
$results5 = invoke-expression -command "commandline5"
$results6 = invoke-expression -command "commandline6"
$results7 = invoke-expression -command "commandline7"
$results8 = invoke-expression -command "commandline8"
$results9 = invoke-expression -command "commandline9"
$results10 = invoke-expression -command "commandline10"
$results11 = invoke-expression -command "commandline11"
$results12 = invoke-expression -command "commandline12"
$results13 = invoke-expression -command "commandline13"
$results14 = invoke-expression -command "commandline14"
$results15 = invoke-expression -command "commandline15"
$results16 = invoke-expression -command "commandline16"
$results17 = invoke-expression -command "commandline17"
$results18 = invoke-expression -command "commandline18"
$results19 = invoke-expression -command "commandline19"
$results20 = invoke-expression -command "commandline20"
$results21 = invoke-expression -command "commandline21"
$results22 = invoke-expression -command "commandline22"
$results23 = invoke-expression -command "commandline23"
$results24 = invoke-expression -command "commandline24"
$results25 = invoke-expression -command "commandline25"
$results26 = invoke-expression -command "commandline26"
$results27 = invoke-expression -command "commandline27"
$results28 = invoke-expression -command "commandline28"
$results29 = invoke-expression -command "commandline29"
$results30 = invoke-expression -command "commandline30"
$results31 = invoke-expression -command "commandline31"
$results32 = invoke-expression -command "commandline32"
$results33 = invoke-expression -command "commandline33"
$results34 = invoke-expression -command "commandline34"
$results35 = invoke-expression -command "commandline35"
$results36 = invoke-expression -command "commandline36"
$results37 = invoke-expression -command "commandline37"
$results38 = invoke-expression -command "commandline38"
$results39 = invoke-expression -command "commandline39"
$results40 = invoke-expression -command "commandline40"
$results41 = invoke-expression -command "commandline41"

